import { Bell, Check, ChevronRight, Command, Lock, Monitor, Radio, Shield, SlidersHorizontal } from 'lucide-react';
import { useState } from 'react';

export function SettingsPage({ role }: { role: string }) {
  const [sound, setSound] = useState(true);
  const [autoCenter, setAutoCenter] = useState(true);
  const [density, setDensity] = useState('Tactical');
  return <div className="h-full overflow-y-auto scrollbar-thin pr-1 space-y-3"><div className="page-heading"><div><div className="eyebrow">Control room preferences / profile</div><h1 className="page-title">System settings</h1><p className="page-subtitle">Tune the command center around the way your team operates.</p></div><div className="badge text-accent-teal bg-accent-teal/10 border border-accent-teal/20"><Shield className="w-3 h-3" /> {role} access</div></div><div className="grid grid-cols-1 xl:grid-cols-3 gap-3"><div className="panel xl:col-span-2 divide-y divide-white/5"><Setting icon={Monitor} title="Display density" description="Choose how much telemetry fits on screen."><div className="segmented">{['Tactical', 'Balanced', 'Comfort'].map((item) => <button key={item} onClick={() => setDensity(item)} className={density === item ? 'active' : ''}>{item}</button>)}</div></Setting><Setting icon={Bell} title="Alert audio" description="Play a tone for critical field alerts."><Toggle checked={sound} onChange={() => setSound(!sound)} /></Setting><Setting icon={Radio} title="Map auto-center" description="Keep the selected asset in the map focal point."><Toggle checked={autoCenter} onChange={() => setAutoCenter(!autoCenter)} /></Setting><Setting icon={SlidersHorizontal} title="Telemetry sampling" description="The current simulation publishes a 500 ms field refresh."><span className="text-xs font-mono text-accent-teal">500 MS</span></Setting></div><div className="space-y-3"><div className="panel p-4"><div className="flex items-center gap-2 text-white"><Command className="w-4 h-4 text-accent-amber" /><span className="panel-title text-white">Command shortcuts</span></div><div className="mt-4 space-y-2">{[['Open operations', 'G O'], ['Plan mission', 'G P'], ['Acknowledge alert', 'A'], ['Pause mission', 'SPACE']].map(([label, key]) => <div key={label} className="flex items-center justify-between text-[11px]"><span className="text-slate-400">{label}</span><kbd>{key}</kbd></div>)}</div></div><div className="panel p-4"><div className="flex items-center gap-2 text-white"><Lock className="w-4 h-4 text-accent-teal" /><span className="panel-title text-white">Session security</span></div><p className="text-[11px] text-slate-500 leading-relaxed mt-3">Your session is protected by Supabase authentication and role-aware controls.</p><button className="w-full flex items-center justify-between text-[10px] uppercase tracking-wider text-slate-400 mt-4 pt-3 border-t border-white/5 hover:text-white">Review access policy <ChevronRight className="w-3 h-3" /></button></div></div></div><div className="flex items-center gap-2 text-[10px] text-slate-600 font-mono"><Check className="w-3.5 h-3.5 text-accent-teal" /> PREFERENCES SAVED LOCALLY</div></div>;
}

function Setting({ icon: Icon, title, description, children }: { icon: typeof Monitor; title: string; description: string; children: React.ReactNode }) { return <div className="flex items-center gap-4 p-4"><div className="w-8 h-8 rounded-md bg-white/5 flex items-center justify-center text-slate-400 flex-shrink-0"><Icon className="w-4 h-4" /></div><div className="flex-1"><div className="text-xs text-white font-semibold">{title}</div><div className="text-[10px] text-slate-600 mt-1">{description}</div></div>{children}</div>; }
function Toggle({ checked, onChange }: { checked: boolean; onChange: () => void }) { return <button onClick={onChange} aria-label="Toggle setting" className={`toggle ${checked ? 'is-on' : ''}`}><span /></button>; }
